make some buffers non-mutable
almusil/rfm69 pull request #17
Opened 2021-01-01 14:17 UTC by rkreis

Using the spi::Write trait, we can make some buffers non-mut. For example, send no longer overwrites the packet buffer.

2021-01-04 06:47 UTC, almusil requested changes
Hi, thank you for this PR. The change looks good just some small nits inline.

2021-01-04 06:47 UTC, almusil commented on src/lib.rs
> +        let val = reg.to_be_bytes();
Now that it does not need to be mut it makes more sense to me to inline this.

2021-01-04 06:47 UTC, almusil commented on src/lib.rs
> +        let val = reg.to_be_bytes();
Same as above

2021-01-04 06:47 UTC, almusil commented on src/lib.rs
> +        let val = reg.to_be_bytes();
Same as above

2021-01-04 06:47 UTC, almusil commented on src/lib.rs
> +        let val = reg.to_be_bytes();
Same as above

2021-01-04 06:47 UTC, almusil commented on src/lib.rs
> +        let val = [reg, len];
Same as above

2021-01-04 06:47 UTC, almusil commented on src/lib.rs
> +        let val = reg.to_be_bytes();
Same as above

2021-01-04 16:23 UTC, rkreis commented
Fixed it :)

2021-01-05 06:10 UTC, almusil approved these changes

2021-01-05 06:10 UTC, merged